name: WBGT Alert

on:
  schedule:
    - cron: '30 9 * * *'  # 日本時間18:30
  workflow_dispatch:       # ✅ これ追加

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Pythonセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: ライブラリインストール
      run: |
        pip install requests beautifulsoup4

    - name: 実行
      run: |
        python wbgt.py
